export default {
  id: "ID",
  class: "Class",
  group: "Group",
  rollNo: "Roll No",
  school: "School",
  firstName: "First Name",
  lastName: "Last Name",
  nationality: "Nationality",
  email: "Email",
  mobileNo: "Mobile No",
  birthDate: "Birth Date",
  religion: "Religion",
  bloodGroup: "Blood Group",
  gender: "Gender",
  maritalStatus: "Marital Status",
  presVillage: "Present Address Village",
  presPO: "Present Address Post Office",
  presUpazilla: "Present Address Upazilla",
  presDistrict: "Present Address District",
  permVillage: "Permanent Address Village",
  permPO: "Permanent Address Post Office",
  permUpazilla: "Permanent Address Upazilla",
  permDistrict: "Permanent Address District",
  fatherFirstName: "Father's First Name",
  fatherLastName: "Father's Last Name",
  fatherProfession: "Father's Profession",
  fatherMobileNo: "Father's Mobile No",
  motherFirstName: "Mother's First Name",
  motherLastName: "Mother's Last Name",
  motherProfession: "Mother's Profession",
  motherMobileNo: "Mother's Mobile No"
};
